server:
  port: 8080

spring:
  application:
    name: article-service
  datasource:
    url: jdbc:mysql://localhost:3306/dumm2
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin5!}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
