spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace